apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9900
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db:5432/cd_auth"
            - name: SPRING_DATASOURCE_USERNAME
              value: "k8s-postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "k8s-password"
            - name: SERVER_NOTIFICATION
              value: "http://notification:9920"
            - name: USER_INFO_URI
              value: "http://auth:9900/user"