apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock
  template:
    metadata:
      labels:
        app: mock
    spec:
      containers:
        - name: mock
          image: mock:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9912
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db:5432/mock"
            - name: SPRING_DATASOURCE_USERNAME
              value: "k8s-postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "k8s-password"
            - name: SERVER_NOTIFICATION
              value: "http://notification:9920"
            - name: SERVICE_AUTH
              value: "http://auth:9900"
            - name: USER_INFO_URI
              value: "http://auth:9900/user"
