apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: k8s-postgres
            - name: POSTGRES_PASSWORD
              value: k8s-password
          volumeMounts:
            - name: pginit
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
        - name: pginit
          configMap:
            name: postgres-init