apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  type: NodePort
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 9920
      targetPort: 9920
      nodePort: 30920
